services:
  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      - node
