services:
  node:
    image: node:20-alpine
    container_name: node
    build:
      context: ../..
      target: development
    ports:
      - '3000:3000'
    env_file:
      - ../../.env.development
    volumes:
      - ../../:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health/kafka"]
      interval: 30s
      timeout: 10s
      retries: 3
