services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    env_file:
      - ../../.env.development
    ports:
      - '${POSTGRES_PORT:-6432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
