name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_ENV: test
  DOCKER_IMAGE_NAME: my-app
  RAILWAY_REGISTRY: railway.app/${{ secrets.RAILWAY_PROJECT_ID }}

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE_NAME }} .

      - name: Tag Docker image
        run: docker tag ${{ env.DOCKER_IMAGE_NAME }} ${{ env.RAILWAY_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Push Docker image
        run: docker push ${{ env.RAILWAY_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
